[book]
authors = ["Mee Foundation"]
language = "en"
multilingual = false
src = "src"
title = "Mee Docs"
[output.html]
theme = "src/theme"
no-section-label = true
additional-js = ["src/theme/logo.js"]
git-repository-url = "https://github.com/MeeProject/ecosystem/tree/mdBook"
fold.enable = true